### ISSUE TITLE
"Object reference not set to an instance of an object." when using AuthorizationUsernamePassword

### ISSUE THREAD

**Issue by stonesvillage** [SuperOffice/SuperOffice.WebApi-Samples#1] opened 2020-11-03 15:26 UTC
Hi!

I've cloned the sample project and got it working when targeting the online SOD environment.

When I try an onsite environment I've successfully used the `AuthorizationTicket` authorization.
But when testing the `AuthorizationUsernamePassword` I get "Object reference not set to an instance of an object.".
Stacktrace:
   at SuperOffice.WebApi.Agents.AgentBase.<SendRequestObject>d__27.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at SuperOffice.WebApi.Agents.ContactAgent.<GetContactEntityAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SuperOffice.WebApi.FullFrameworkSample.Program.<Onsite>d__5.MoveNext() in C:\Source\Lekstuga\SuperOffice\SuperOffice.WebApi-Samples\SuperOffice.WebApi.NetCoreSample\Program.cs:line 77
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SuperOffice.WebApi.FullFrameworkSample.Program.<Main>d__4.MoveNext()

I'm sure the username and password is correct.

Regards

Gunnar Stensby, i-Centrum AB

**Comment by AnthonyYates** [comment] 2020-11-04 10:48
Hi Gunnar,

Did you remember to assign the AuthorizationUsernamePassword to the WebApiConfiguration.Authorization property?

```C#
WebApiConfiguration config = new WebApiConfiguration(baseUrl);
var authorization = new AuthorizationUsernamePassword("name", "pass");

// assign the authorization instance to the WebApiConfiguration.Authorization property
config.Authorization = authorization;

var ca = new ContactAgent(config);
var ce = ca.GetContactEntityAsync(25).Result;
```

**Comment by stonesvillage** [comment] 2020-11-04 11:07
Hi Tony,
This is my code:
```c#
var config = new WebApiConfiguration(baseUrl);
config.Authorization = new AuthorizationUsernamePassword("username", "password");
var contactAgent = new ContactAgent(config);
var contact = await contactAgent.GetContactEntityAsync(1); // throws Object reference not set to an instance of an object.
```
SuperOffice info:
Version: 9.1 R3
Netserver: SuperOffice 9.1 Build Release9_C-2020.10.06-03

Regards
Gunnar

**Comment by AnthonyYates** [comment] 2020-11-04 14:55
Hi Gunnar,

I was only able to reproduce your results only under the following conditions:
* the authorization was not assigned to the web configuration
* the credentials were wrong

I have since fixed the `NullReferenceException` when using bad username/password credentials. It will now throw an Unauthorized exception as expected.

I am happy to share with you proof of a working example with our publicly available onsite API, the same one we use for documentation playground, but not here. I'll send you an email.

Thanks for your feedback! One bug closed, and will be included in the next preview - published in one weeks time.

**Closed by AnthonyYates** 2020-11-04 14:55 UTC
Labels: investigating, question
