### ISSUE TITLE
Using RequestOptions instantly throw exception

### ISSUE THREAD

**Issue by andreas-nkb** [SuperOffice/SuperOffice.WebApi-Samples#11] opened 2021-12-01 14:14 UTC
Hi!

Since version 9.2.7935, all requests that use RequestOptions instantly throws "SendRequest timed out". 

For example 
```
var contactAgent = new ContactAgent(config);
var contactEntity = await contactAgent.GetContactEntityAsync(1, new RequestOptions { LanguageCode = "EN" });
```
Does **not** work but 

```
var contactAgent = new ContactAgent(config);
var contactEntity = await contactAgent.GetContactEntityAsync(1);
```

does work.

Using RequestOptions did work in the earlier releases, for example preview3.

Would be really nice if this could be fixed!

This happens both in .NET Core 3.1 and .Net 6.0.

**Comment by SuperOfficeDevNet** [comment] 2021-12-01 15:08
Hi Andreas! 

We added the possibility to have a timeout after preview3, and the default is 30 seconds, set in the WebApiOptions.
When RequestOptions are passed in to a method, it should clone and update WebApiOptions (RequestOptions) for that invocation. I haven't had a change to debug it yet, but it could be it's not setting the Timeout correctly.

Does explicitly setting it help? Maybe it needs a longer time?

```csharp
new RequestOptions() 
{
    Timeout = TimeSpan.FromSeconds(100),
    LanguageCode = "EN" 
}
```

Best regards.

**Comment by SuperOfficeDevNet** [comment] 2021-12-01 15:33
OK, we were able to find the cause of the problem and fix it. It should respect the default timeout with 10.0.4. 

Closing this issue.

**Closed by SuperOfficeDevNet** 2021-12-01 15:33 UTC
Labels: investigating
